"""Builds app/data.js from the Hanzi Writer character data (npm: hanzi-writer-data).

Run from this folder:  npm install && python3 build_data.py
The stroke names below were checked by eye against rendered stroke sheets.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, 'node_modules', 'hanzi-writer-data') + os.sep
OUT = os.path.join(HERE, '..', 'app', 'data.js')

# (char, pinyin, meaning, level, stroke names in order) -- names checked by eye against rendered sheets
ROWS = [
    # level 1: 1-4 strokes
    ('一', 'yī', 'one', 1, '橫'),
    ('二', 'èr', 'two', 1, '橫 橫'),
    ('十', 'shí', 'ten', 1, '橫 豎'),
    ('人', 'rén', 'person', 1, '撇 捺'),
    ('三', 'sān', 'three', 1, '橫 橫 橫'),
    ('大', 'dà', 'big', 1, '橫 撇 捺'),
    ('小', 'xiǎo', 'small', 1, '豎鉤 點 點'),
    ('口', 'kǒu', 'mouth', 1, '豎 橫折 橫'),
    ('山', 'shān', 'mountain', 1, '豎 豎折 豎'),
    ('土', 'tǔ', 'earth, soil', 1, '橫 豎 橫'),
    ('女', 'nǚ', 'woman', 1, '撇點 撇 橫'),
    ('子', 'zǐ', 'child', 1, '橫撇 豎鉤 橫'),
    ('日', 'rì', 'sun, day', 1, '豎 橫折 橫 橫'),
    ('月', 'yuè', 'moon, month', 1, '撇 橫折鉤 橫 橫'),
    ('木', 'mù', 'tree, wood', 1, '橫 豎 撇 捺'),
    ('水', 'shuǐ', 'water', 1, '豎鉤 橫撇 撇 捺'),
    ('火', 'huǒ', 'fire', 1, '點 撇 撇 捺'),
    ('中', 'zhōng', 'middle, center', 1, '豎 橫折 橫 豎'),
    ('心', 'xīn', 'heart', 1, '點 臥鉤 點 點'),
    ('天', 'tiān', 'sky, day', 1, '橫 橫 撇 捺'),
    ('不', 'bù', 'not', 1, '橫 撇 豎 點'),
    # level 2: 5-9 strokes
    ('永', 'yǒng', 'forever', 2, '點 橫折鉤 橫撇 撇 捺'),
    ('白', 'bái', 'white', 2, '撇 豎 橫折 橫 橫'),
    ('田', 'tián', 'field', 2, '豎 橫折 橫 豎 橫'),
    ('生', 'shēng', 'to be born, life', 2, '撇 橫 橫 豎 橫'),
    ('本', 'běn', 'root, origin', 2, '橫 豎 撇 捺 橫'),
    ('目', 'mù', 'eye', 2, '豎 橫折 橫 橫 橫'),
    ('好', 'hǎo', 'good', 2, '撇點 撇 橫 橫撇 豎鉤 橫'),
    ('我', 'wǒ', 'I, me', 2, '撇 橫 豎鉤 提 斜鉤 撇 點'),
    ('你', 'nǐ', 'you', 2, '撇 豎 撇 橫撇 豎鉤 點 點'),
    ('車', 'chē', 'car, vehicle', 2, '橫 豎 橫折 橫 橫 橫 豎'),
    ('的', 'de', 'of (possessive particle)', 2, '撇 豎 橫折 橫 橫 撇 橫折鉤 點'),
    ('門', 'mén', 'door, gate', 2, '豎 橫折鉤 橫 橫 豎 橫折鉤 橫 橫'),
    ('東', 'dōng', 'east', 2, '橫 豎 橫折 橫 橫 豎 撇 捺'),
    # level 3: 10+ strokes
    ('馬', 'mǎ', 'horse', 3, '橫 豎 橫 橫 豎 橫折鉤 點 點 點 點'),
    ('書', 'shū', 'book', 3, '橫折 橫 橫 橫 豎 橫 豎 橫折 橫 橫'),
    ('們', 'men', 'plural marker for people', 3, '撇 豎 豎 橫折鉤 橫 橫 豎 橫折鉤 橫 橫'),
    ('鳥', 'niǎo', 'bird', 3, '撇 豎 橫折 橫 橫 橫 橫折鉤 點 點 點 點'),
    ('國', 'guó', 'country', 3, '豎 橫折 橫 豎 橫折 橫 橫 斜鉤 撇 點 橫'),
    ('開', 'kāi', 'to open', 3, '豎 橫折鉤 橫 橫 豎 橫折鉤 橫 橫 橫 橫 撇 豎'),
    ('電', 'diàn', 'electricity', 3, '橫 豎 橫折鉤 豎 點 點 點 點 豎 橫折 橫 橫 豎彎鉤'),
    ('愛', 'ài', 'love', 3, '撇 點 點 點 點 橫鉤 點 臥鉤 點 點 撇 橫撇 捺'),
    ('說', 'shuō', 'to speak', 3, '點 橫 橫 橫 豎 橫折 橫 點 撇 豎 橫折 橫 撇 豎彎鉤'),
    ('語', 'yǔ', 'language', 3, '點 橫 橫 橫 豎 橫折 橫 橫 豎 橫折 橫 豎 橫折 橫'),
    ('樂', 'lè', 'happy (also yuè, music)', 3, '撇 豎 橫折 橫 橫 撇折 撇折 點 撇折 撇折 點 橫 豎 撇 捺'),
    ('學', 'xué', 'to learn', 3, '點 豎 橫 橫 撇 點 撇 點 橫折 橫 橫 點 橫鉤 橫撇 豎鉤 橫'),
    ('龍', 'lóng', 'dragon', 3, '點 橫 點 撇 橫 豎 橫折鉤 橫 橫 橫 豎折折鉤 橫 豎彎鉤 橫 橫 橫'),
]

KNOWN = {'點', '橫', '豎', '撇', '捺', '提', '橫折', '橫鉤', '橫撇', '橫折鉤', '豎折', '豎鉤', '豎彎鉤',
         '斜鉤', '臥鉤', '撇折', '撇點', '豎折折鉤'}


def main():
    out = []
    problems = []
    for c, py, en, lv, names in ROWS:
        d = json.load(open(BASE + c + '.json'))
        nm = names.split()
        n = len(d['strokes'])
        if len(nm) != n:
            problems.append(f'{c}: {n} strokes in data but {len(nm)} names')
            continue
        for x in nm:
            if x not in KNOWN:
                problems.append(f'{c}: unknown stroke name {x}')
        out.append({
            'c': c, 'py': py, 'en': en, 'lv': lv,
            's': [{'d': d['strokes'][i], 'm': d['medians'][i], 't': nm[i]} for i in range(n)],
        })
    if problems:
        print('\n'.join(problems))
        sys.exit(1)
    # stroke-count sanity per level
    for lv, lo, hi in ((1, 1, 4), (2, 5, 9), (3, 10, 16)):
        bad = [x['c'] for x in out if x['lv'] == lv and not (lo <= len(x['s']) <= hi)]
        if bad:
            print('level mismatch', lv, bad)
            sys.exit(1)
    payload = json.dumps({'chars': out}, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* Stroke outlines and medians: Make Me a Hanzi via hanzi-writer-data (Arphic Public License). See ARPHICPL.TXT. Generated by tools/build_data.py. */\n')
        f.write('window.BISHUN_DATA=' + payload + ';\n')
    print('ok', len(out), 'characters', sum(len(x['s']) for x in out), 'strokes')


if __name__ == '__main__':
    main()
